#!/usr/bin/env python
"""
Regenerate paper/tables/extension.tex from the locked replication-cohort traces.

Data sources (both released):
  - results/grid_ext/ext_ledger.jsonl                    (6 fixed policies, budgets {60,300}, 2 seeds)
  - results/grid_ext/results/raw/*learned_v2*_summary.json (learned-v2, 3 seeds)
  - data/extension_manifest.json                         (locked 24-instance cohort)

Verdict rule (symmetric, frozen here in code):
  Delta = exploration_mean - bound_driven_mean  (positive = bound-driven better)
    split                 : exploration_mean >= 2 * bound_driven_mean AND Delta > 2
    exploration-advantage : Delta < -2
    bound-advantage       : Delta > +2 (and not split)
    parity                : |Delta| <= 2
    n/f                   : bound-driven or exploration class mean unavailable
"""

from __future__ import annotations

import json
import re
import statistics
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LEDGER = ROOT / "results" / "grid_ext" / "ext_ledger.jsonl"
RAW = ROOT / "results" / "grid_ext" / "results" / "raw"
MANIFEST = ROOT / "data" / "extension_manifest.json"
OUT = ROOT / "paper" / "tables" / "extension.tex"

BOUND_POLICIES = ["best_bound", "depth_first", "hybrid_best_bound_depth"]
EXPLORATION_POLICIES = ["greedy_score", "random_uniform", "best_estimate",
                        "boltzmann_adaptive", "safeguarded_hybrid"][:3]  # see note below
# NOTE: the extension grid ran {best_bound, depth_first, hybrid, best_estimate,
# boltzmann_adaptive, random_uniform}; exploration class = the three non-bound ones.
EXPLORATION_POLICIES = ["best_estimate", "boltzmann_adaptive", "random_uniform"]


def collect_fixed(optima: dict):
    """instance -> policy -> [gap%] at budget 300, scored against manifest optima."""
    gaps: dict[str, dict[str, list[float]]] = defaultdict(lambda: defaultdict(list))
    pat = re.compile(r"^p45x_(.+?)_([a-z_]+?)_(b\d+)_(s\d+)$")
    for line in LEDGER.read_text().splitlines():
        r = json.loads(line)
        m = pat.match(r["run_id"])
        if not m:
            continue
        inst, pol, budget, _seed = m.groups()
        if budget != "b300":
            continue
        inc = r.get("incumbent")
        opt = optima.get(inst)
        if inc is None or opt is None:
            continue
        gaps[inst][pol].append(100.0 * (inc - opt) / abs(opt))
    return gaps


def collect_learned_v2(optima: dict):
    """instance -> [gap%] at budget 300 over 3 seeds, scored against manifest optima."""
    gaps: dict[str, list[float]] = defaultdict(list)
    for f in RAW.glob("p45x_*_learned_v2_b300_s*_summary.json"):
        d = json.loads(f.read_text())
        m = re.match(r"^p45x_(.+?)_learned_v2_b300_s\d+(?:_\d+)?$", d["run_id"])
        if not m:
            continue
        inst = m.group(1)
        inc = d.get("incumbent_objective")
        opt = optima.get(inst)
        if inc is None or opt is None:
            continue
        gaps[inst].append(100.0 * (inc - opt) / abs(opt))
    return gaps


def verdict(bd, ex):
    if bd is None or ex is None:
        return "n/f"
    delta = ex - bd
    if ex >= 2 * bd and delta > 2:
        return "split"
    if delta < -2:
        return "exploration"
    if delta > 2:
        return "bound-driven"
    return "parity"


def fmt(x):
    if x is None:
        return "--"
    if abs(x) < 0.005:  # solver-tolerance excursions round to 0.00
        x = 0.0
    return f"{x:.2f}"


def main():
    manifest = json.loads(MANIFEST.read_text())
    items = manifest["instances"] if isinstance(manifest, dict) and "instances" in manifest else manifest
    cohort = [i["instance_name"] for i in items]
    optima = {i["instance_name"]: i["optimum"] for i in items}
    assert len(cohort) == 24, f"locked cohort must have 24 instances, got {len(cohort)}"

    fixed = collect_fixed(optima)
    lv2 = collect_learned_v2(optima)

    rows = []
    counts = defaultdict(int)
    for inst in cohort:
        bd_gaps = [g for p in BOUND_POLICIES for g in fixed.get(inst, {}).get(p, [])]
        ex_gaps = [g for p in EXPLORATION_POLICIES for g in fixed.get(inst, {}).get(p, [])]
        bd = statistics.fmean(bd_gaps) if bd_gaps else None
        ex = statistics.fmean(ex_gaps) if ex_gaps else None
        lv = statistics.fmean(lv2[inst]) if lv2.get(inst) else None
        v = verdict(bd, ex)
        counts[v] += 1
        rows.append((inst, bd, ex, lv, v))

    lines = [
        "% auto-generated by scripts/make_extension_table.py -- do not edit by hand",
        "\\begin{table}[htbp]",
        "\\centering\\scriptsize\\setlength{\\tabcolsep}{3pt}",
        "\\caption{Replication cohort (24 locked MIPLIB hold-out instances, 300\\,s): mean incumbent gap (\\%) versus official optima for the bound-driven mean (three policies, two seeds), the exploration mean (three policies, two seeds), and the frozen learned-v2 selector (three seeds). Verdicts use a symmetric frozen rule on $\\Delta = $ exploration $-$ bound-driven: parity ($|\\Delta|\\le 2$ points), exploration-advantage ($\\Delta<-2$), bound-advantage ($\\Delta>2$), and split (bound-driven better by at least $2\\times$ and $\\Delta>2$). A split in the same direction recurs in exactly one cell (\\texttt{railway\\_8\\_1\\_0}, an $8.7\\times$ class-mean ratio).}",
        "\\label{tab:extension}",
        "\\begin{tabular}{lrrrl}",
        "\\toprule",
        "Instance & Bound-driven & Exploration & Learned-v2 & Verdict \\\\",
        "\\midrule",
    ]
    for inst, bd, ex, lv, v in rows:
        esc = inst.replace("_", "\\_")
        cells = f"{esc} & {fmt(bd)} & {fmt(ex)} & {fmt(lv)} & {v}"
        if v == "split":  # highlight the single split row
            cells = " & ".join(f"\\textbf{{{c}}}" for c in cells.split(" & "))
        lines.append(cells + " \\\\")
    lines += [
        "\\midrule",
        f"\\multicolumn{{5}}{{l}}{{Verdict counts (parity/expl./bound/split/n-f): {counts['parity']}/{counts['exploration']}/{counts['bound-driven']}/{counts['split']}/{counts['n/f']}}} \\\\",
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}")
    print(f"counts: {dict(counts)} (total {sum(counts.values())})")
    for inst, bd, ex, lv, v in rows:
        if v in ("split", "bound-driven", "exploration"):
            print(f"  {v:14s} {inst}: BD={fmt(bd)} EX={fmt(ex)} lv2={fmt(lv)}")


if __name__ == "__main__":
    main()
