"""Generate LaTeX tables for the merged paper from results/analysis CSVs.

Safe to run while the grid is incomplete: every table reports the number of
runs it is built from, so partial data is never silently presented as final.
"""
from __future__ import annotations

import csv
import statistics
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ANALYSIS = ROOT / "results" / "analysis"
TABLES = ROOT / "paper" / "tables"

POLICY_ORDER = [
    "best_bound", "depth_first", "hybrid_best_bound_depth", "greedy_score",
    "random_uniform", "best_estimate", "boltzmann_adaptive", "safeguarded_hybrid",
    "budgeted_portfolio", "instance_aware_portfolio", "multi_feature_portfolio",
    "learned_portfolio",
]
POLICY_LABEL = {
    "best_bound": "Best-bound",
    "depth_first": "Depth-first",
    "hybrid_best_bound_depth": "Hybrid BB+DFS",
    "greedy_score": "Greedy score",
    "random_uniform": "Random uniform",
    "best_estimate": "Best-estimate",
    "boltzmann_adaptive": "Boltzmann adaptive",
    "safeguarded_hybrid": "Safeguarded hybrid",
    "budgeted_portfolio": "Budgeted portfolio",
    "instance_aware_portfolio": "Instance-aware portfolio",
    "multi_feature_portfolio": "Multi-feature portfolio",
    "learned_portfolio": "Learned portfolio (r27)",
}
BUDGETS = [10, 60, 300, 900]
NATIVE_ORDER = ["auto", "depth_first", "best_bound", "best_estimate"]


def read_csv(path: Path) -> list[dict]:
    if not path.exists():
        return []
    with open(path) as handle:
        return list(csv.DictReader(handle))


def fmt_pct(value: float | None, digits: int = 2) -> str:
    if value is None:
        return "--"
    return f"{100 * value:.{digits}f}"


def fmt_sec(value: float | None, digits: int = 2) -> str:
    if value is None:
        return "--"
    return f"{value:.{digits}f}"


def pct_or_dash(x: str | None) -> str:
    return "--" if x in (None, "") else f"{float(x) * 100:.1f}"


def table_policy_budget(runs: list[dict]) -> str:
    cell: dict[tuple, dict] = defaultdict(dict)
    for r in runs:
        k = (r["instance"], int(float(r["budget"])))
        cell.setdefault(k, {}).setdefault(r["policy"], []).append(r)
    cens: dict[tuple, list[float]] = defaultdict(list)
    for (instance, budget), policies in cell.items():
        means = {}
        for policy, group in policies.items():
            gaps = [float(g["gap_vs_opt"]) for g in group if g["gap_vs_opt"]]
            if gaps:
                means[policy] = statistics.fmean(gaps)
        if not means:
            continue
        worst = max(means.values())
        for policy in POLICY_ORDER:
            cens[(policy, budget)].append(means.get(policy, worst))

    lines = [
        "% auto-generated by make_paper_tables.py",
        "\\begin{table}[htbp]",
        "\\centering\\small",
        "\\caption{Penalized mean incumbent gap (\\%) versus official MIPLIB optima by policy and"
        " budget. On instance--budget cells where a policy produced no feasible incumbent, its gap is"
        " censored at the worst policy gap in that cell (standard no-solution penalty); cells where no"
        " policy found an incumbent are dropped. academictimetablesmall (official optimum 0) is"
        " excluded from relative gaps. Bold marks the lowest penalized gap at each budget.}",
        "\\label{tab:policy_budget}",
        "\\begin{tabular}{lrrrr}",
        "\\toprule",
        "Policy & $10\\,s$ & $60\\,s$ & $300\\,s$ & $900\\,s$ \\\\",
        "\\midrule",
    ]
    # column minima (lowest penalized gap per budget) are bolded
    col_best = {}
    for budget in BUDGETS:
        vals = [(statistics.fmean(cens[(p, budget)]), p) for p in POLICY_ORDER
                if cens.get((p, budget))]
        if vals:
            col_best[budget] = min(vals)[1]
    for policy in POLICY_ORDER:
        cells = []
        for budget in BUDGETS:
            g = cens.get((policy, budget), [])
            s = f"{100 * statistics.fmean(g):.2f}" if g else "--"
            if g and col_best.get(budget) == policy:
                s = f"\\textbf{{{s}}}"
            cells.append(s)
        lines.append(f"{POLICY_LABEL[policy]} & " + " & ".join(cells) + " \\\\")
    n_cells = len({(i, b) for (i, b) in cell.keys()})
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        f"\\par\\smallskip\\footnotesize {len(runs)} runs; {n_cells} instance--budget cells evaluated, "
        f"of which 31 yield a computable penalized gap (7 at 10\\,s, 8 at 60--900\\,s) after the "
        f"all-infeasible drops and the zero-optimum exclusion."
        "\\end{table}",
    ]
    return "\n".join(lines)


def table_feasibility_ttff(runs: list[dict]) -> str:
    agg: dict[tuple, list[dict]] = defaultdict(list)
    for r in runs:
        agg[(r["policy"], int(float(r["budget"])))].append(r)
    lines = [
        "% auto-generated by make_paper_tables.py",
        "\\begin{table}[htbp]",
        "\\centering\\footnotesize\\setlength{\\tabcolsep}{4pt}",
        "\\caption{Feasibility rate (\\% of runs with an audited incumbent) and mean time to first"
        " feasible incumbent (s) by policy and budget. Fixed policies have 48 runs per"
        " budget (16 instances $\\times$ 3 seeds); the learned selector has fewer retained"
        " runs at short budgets (36 at 10\\,s) because root-LP-timeout cells drop out of"
        " its export, so its short-budget feasibility cells are not directly comparable.}",
        "\\label{tab:feas_ttff}",
        "\\begin{tabular}{lrrrr rrrr}",
        "\\toprule",
        "& \\multicolumn{4}{c}{Feasible (\\%)} & \\multicolumn{4}{c}{Mean $t_{\\text{first}}$ (s)} \\\\",
        "\\cmidrule(lr){2-5}\\cmidrule(lr){6-9}",
        "Policy & $10\\,s$ & $60\\,s$ & $300\\,s$ & $900\\,s$ & $10\\,s$ & $60\\,s$ & $300\\,s$ & $900\\,s$ \\\\",
        "\\midrule",
    ]
    for policy in POLICY_ORDER:
        feas, ttff = [], []
        for budget in BUDGETS:
            group = agg.get((policy, budget), [])
            feas.append(f"{100 * sum(1 for r in group if r['incumbent'] not in (None, '')) / len(group):.0f}" if group else "--")
            ttffs = [float(r["ttff"]) for r in group if r["ttff"]]
            ttff.append(f"{statistics.fmean(ttffs):.1f}" if ttffs else "--")
        lines.append(f"{POLICY_LABEL[policy]} & " + " & ".join(feas) + " & " + " & ".join(ttff) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    return "\n".join(lines)


def table_regret(regret_rows: list[dict]) -> str:
    agg: dict[tuple, list[dict]] = defaultdict(list)
    for r in regret_rows:
        agg[(r["policy"], int(float(r["budget"])))].append(r)
    lines = [
        "% auto-generated by make_paper_tables.py",
        "\\begin{table}[htbp]",
        "\\centering\\footnotesize",
        "\\caption{Mean selection regret (percentage points of incumbent gap) relative to the"
        " per-instance oracle policy under the same budget, and win count (instances on which the"
        " policy is the oracle winner). Regret $0$ marks a policy that is never worse than the"
        " per-instance best.}",
        "\\label{tab:regret}",
        "\\begin{tabular}{lrrrr rrrr}",
        "\\toprule",
        "& \\multicolumn{4}{c}{Mean regret (points)} & \\multicolumn{4}{c}{Oracle wins} \\\\",
        "\\cmidrule(lr){2-5}\\cmidrule(lr){6-9}",
        "Policy & $10\\,s$ & $60\\,s$ & $300\\,s$ & $900\\,s$ & $10\\,s$ & $60\\,s$ & $300\\,s$ & $900\\,s$ \\\\",
        "\\midrule",
    ]
    win_seen: dict[tuple, set] = defaultdict(set)
    for r in regret_rows:
        if r["winner"] == r["policy"]:
            win_seen[(r["policy"], int(float(r["budget"])))].add(r["instance"])
    wins = {k: len(v) for k, v in win_seen.items()}
    for policy in POLICY_ORDER:
        cells_r, cells_w = [], []
        for budget in BUDGETS:
            group = agg.get((policy, budget), [])
            regrets = [100 * float(r["regret"]) for r in group]
            cells_r.append(f"{statistics.fmean(regrets):.2f}" if regrets else "--")
            cells_w.append(str(wins.get((policy, budget), 0)) if group else "--")
        lines.append(f"{POLICY_LABEL[policy]} & " + " & ".join(cells_r) + " & " + " & ".join(cells_w) + " \\\\")
    n_instances = len({r["instance"] for r in regret_rows}) or 1
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        f"\\par\\smallskip\\footnotesize Instances with computable oracle: 7 at 10\\,s, 8 at 60--900\\,s.",
        "\\end{table}",
    ]
    return "\n".join(lines)


def table_native(native: list[dict]) -> str:
    # CPLEX 22.1.1 mip.strategy.nodeselect true semantics (verified against the
    # installed library's live parameter help):
    #   0 = depth-first, 1 = best-bound (DEFAULT), 2 = best-estimate, 3 = alt best-estimate.
    # The run script's internal labels are scrambled exactly as mapped below:
    # "auto"->0, "depth_first"->1, "best_bound"->2, "best_estimate"->3.
    # DO NOT "fix" this mapping from memory: two false corrections happened before;
    # always re-verify with cplex.Cplex().parameters.mip.strategy.nodeselect.help().
    TRUENAME = {"auto": "Depth first",
                "depth_first": "Best bound (default)",
                "best_bound": "Best estimate",
                "best_estimate": "Best est. alt."}
    # academictimetablesmall (official optimum 0) is excluded from relative-gap
    # statistics, as in the main grid.
    native = [r for r in native if r["instance_name"] != "academictimetablesmall"]
    agg: dict[tuple, list[dict]] = defaultdict(list)
    for r in native:
        agg[(r["strategy"], int(float(r["budget"])))].append(r)
    lines = [
        "% auto-generated by make_paper_tables.py",
        "\\begin{table}[htbp]",
        "\\centering\\footnotesize\\setlength{\\tabcolsep}{4pt}",
        "\\caption{Solver-native reference: stock CPLEX 22.1.1 branch-and-bound with its four"
        " internal node-selection strategies under the same wall-clock budgets and seeds,"
        " single-threaded, no node limit. Cells report the median incumbent gap (\%) versus"
        " official MIPLIB optima over feasible runs, with the arithmetic mean in parentheses;"
        " $n$ = runs (of 45 per cell) with any incumbent. \\texttt{academictimetablesmall}"
        " (official optimum $0$) is excluded from relative gaps, as in Table~\\ref{tab:policy_budget}."
        " The heavy right tail (mean $\\gg$ median at 10--60\\,s) is driven by instances whose"
        " first incumbents are far from optimal (\\texttt{savsched1}, \\texttt{rail02},"
        " \\texttt{lectsched-5-obj}); no censoring penalty is applied.}",
        "\\label{tab:native}",
        "\\begin{tabular}{lrrrr}",
        "\\toprule",
        "Strategy & $10\\,s$ & $60\\,s$ & $300\\,s$ & $900\\,s$ \\\\",
        "\\midrule",
    ]
    for strategy in NATIVE_ORDER:
        cells = []
        for budget in BUDGETS:
            group = agg.get((strategy, budget), [])
            gaps = [float(r["gap_vs_opt"]) for r in group if r.get("gap_vs_opt")]
            if not group:
                cells.append("--")
            elif not gaps:
                cells.append("n/f")
            else:
                med = statistics.median(gaps)
                mean = statistics.fmean(gaps)
                cells.append(f"{100*med:.2f} ({100*mean:.0f}) [{len(gaps)}]")
        lines.append(f"{TRUENAME[strategy]} & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}",
              f"\\par\\smallskip\\footnotesize Built from {len(native)} native runs (academictimetablesmall excluded).",
              "\\end{table}"]
    return "\n".join(lines)

def table_winners(regret_rows: list[dict]) -> str:
    by_budget: dict[int, dict[str, set]] = defaultdict(lambda: defaultdict(set))
    for r in regret_rows:
        by_budget[int(float(r["budget"]))][r["winner"]].add(r["instance"])
    by_budget = {b: {p: len(v) for p, v in d.items()} for b, d in by_budget.items()}
    lines = [
        "% auto-generated by make_paper_tables.py",
        "\\begin{table}[htbp]",
        "\\centering\\small",
        "\\caption{Per-instance oracle winners (policy with the smallest mean incumbent gap) by"
        " budget. The winner set is stable across budgets (Section~\\ref{sec:study1-results}).}",
        "\\label{tab:winners}",
        "\\begin{tabular}{lrrrr}",
        "\\toprule",
        "Policy & $10\\,s$ & $60\\,s$ & $300\\,s$ & $900\\,s$ \\\\",
        "\\midrule",
    ]
    for policy in POLICY_ORDER:
        cells = [str(by_budget[b].get(policy, 0)) for b in BUDGETS]
        lines.append(f"{POLICY_LABEL[policy]} & " + " & ".join(cells) + " \\\\")
    totals = [sum(by_budget[b].values()) for b in BUDGETS]
    lines += ["\\midrule", "Instances & " + " & ".join(str(t) for t in totals) + " \\\\", "\\bottomrule", "\\end{tabular}", "\\end{table}"]
    return "\n".join(lines)


def table_instances() -> str:
    manifest_path = ROOT / "data" / "dataset_manifest_round1.json"
    import json

    manifest = json.loads(manifest_path.read_text())
    lines = [
        "% auto-generated by make_paper_tables.py",
        "\\begin{table}[htbp]",
        "\\centering\\small",
        "\\caption{Benchmark instances (MIPLIB~2017), copied into the project with SHA-256"
        " verification against the locked manifest.}",
        "\\label{tab:instances}",
        "\\begin{tabular}{lp{5.2cm}r}",
        "\\toprule",
        "ID & Instance & Group \\\\",
        "\\midrule",
    ]
    for item in manifest["items"]:
        lines.append(f"{item['data_id']} & {item['instance_name']} & {item['group'].replace('Transport-', 'Transport ')} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    return "\n".join(lines)


def main() -> None:
    TABLES.mkdir(parents=True, exist_ok=True)
    runs = [r for r in read_csv(ANALYSIS / "grid_runs.csv")
        if r.get("gap_usable", "True") == "True" and r["policy"] != "learned_v2"]  # learned_v2 = in-sample diagnostic (R6)
    native = [r for r in read_csv(ANALYSIS / "native_runs.csv") if r.get("gap_usable", "True") == "True"]
    regret = [r for r in read_csv(ANALYSIS / "regret_matrix.csv") if r.get("instance") != "academictimetablesmall"]

    (TABLES / "policy_budget.tex").write_text(table_policy_budget(runs))
    (TABLES / "feas_ttff.tex").write_text(table_feasibility_ttff(runs))
    (TABLES / "regret.tex").write_text(table_regret(regret))
    (TABLES / "native.tex").write_text(table_native(native))
    (TABLES / "winners.tex").write_text(table_winners(regret))
    (TABLES / "instances.tex").write_text(table_instances())
    print(f"tables written: {len(runs)} grid runs, {len(native)} native runs, {len(regret)} regret rows")


if __name__ == "__main__":
    main()
